const KEY='posUdemyProgressV1';const store={get:()=>localStorage.getItem(KEY),set:v=>{try{localStorage.setItem(KEY,v)}catch{}}};
const modules=[
{name:'Linux & Administração',area:'Infra',hours:28,checkpoint:'NOC Jr.',project:'Ubuntu Server com SSH, Nginx, firewall, logs e script Bash',course:'Aprenda tudo sobre o Linux! — Vitor Mazuco',study:['Terminal e filesystem','Permissões, usuários e grupos','Processos e systemd','Pacotes e SSH','Rede e firewall','Logs, Bash e hardening'],skip:['História extensa','GUI básica já dominada','Tópicos avançados fora do objetivo']},
{name:'Redes & Troubleshooting',area:'Infra',hours:30,checkpoint:'NOC Jr.',project:'Lab no Packet Tracer ou GNS3: VLANs, roteamento, DHCP/DNS e diagnóstico com ping, traceroute e Wireshark',course:'Curso preparatório de CCNA (escolher curso atual em português antes de comprar)',study:['OSI/TCP-IP e endereçamento IPv4/sub-redes','Switching, VLANs e trunk','Roteamento estático e OSPF','DHCP, DNS e NAT','ACLs e noções de segurança de rede','Troubleshooting com ping, traceroute e Wireshark'],skip:['Hardware e cabeamento antigo','Protocolos legados fora do exame']},
{name:'NOC & Zabbix',area:'NOC',hours:22,checkpoint:'NOC Jr.',project:'Zabbix + Grafana monitorando Windows e Linux',course:'Curso de Zabbix 7! — Vitor Mazuco',study:['Hosts, templates, items e triggers','Discovery e agentes','SNMP/ICMP','Dashboards e alertas','Grafana e API'],skip:['Integrações sem relação com o laboratório']},
{name:'Windows Server & Infra',area:'Infra',hours:18,checkpoint:'Infra Jr.',project:'AD, DNS, DHCP, GPO, file server e automações PowerShell',course:'Revisão prática de Windows Server / AD / PowerShell',study:['AD DS','DNS e DHCP','GPO e permissões','Shares','PowerShell e troubleshooting'],skip:['Conteúdo introdutório que você já domina']},
{name:'AWS Cloud',area:'Cloud',hours:24,checkpoint:'Cloud Jr.',project:'AWS 3-tier: Load Balancer + EC2 + RDS + CloudWatch',course:'AWS Solutions Architect Associate SAA-C03 — Marlon Anesi',study:['IAM','EC2 e S3','VPC, subnets e rotas','IGW, NAT e Security Groups','RDS, Load Balancer e Auto Scaling','CloudWatch, Route 53 e custos'],skip:['Detalhes de serviços que não entram no projeto']},
{name:'Git & GitHub',area:'DevOps',hours:8,checkpoint:'Base DevOps',project:'Repositório profissional com README, issues e documentação',course:'Git e GitHub — fundamentos práticos',study:['Commit, push, pull e branches','Merge, revert e stash','Pull Requests','README e Issues'],skip:['História extensa do Git']},
{name:'Docker',area:'DevOps',hours:17,checkpoint:'DevOps Jr.',project:'Docker Compose com Nginx, aplicação e PostgreSQL',course:'Docker — Dominando criação e gerenciamento de containers',study:['Images e containers','Dockerfile','Volumes e networks','Compose','Registry, logs e troubleshooting'],skip:['Repetição desnecessária de Linux']},
{name:'Terraform',area:'IaC',hours:18,checkpoint:'Cloud/DevOps Jr.',project:'Recriar a infraestrutura AWS do projeto usando Terraform',course:'Terraform para AWS — Mateus Müller',study:['Providers e resources','VPC, subnets e rotas','Variables e outputs','Modules','State e backend remoto'],skip:['Cloud providers fora do foco inicial']},
{name:'CI/CD',area:'DevOps',hours:8,checkpoint:'DevOps Jr.',project:'Pipeline automático de teste, build de imagem e deploy',course:'GitHub Actions: Guia Completo — Do Zero ao Deploy',study:['Workflows YAML','Jobs, steps e triggers','Secrets e artifacts','Environments','Build Docker e deploy'],skip:['Integrações que não serão usadas']},
{name:'Kubernetes',area:'DevOps',hours:24,checkpoint:'DevOps/SRE Jr.',project:'Cluster Kubernetes com deploy, probes, ingress e monitoramento',course:'Escolher/revalidar curso em 2027',study:['Pods, Deployments e Services','ConfigMaps e Secrets','Ingress e volumes','RBAC e namespaces','Probes, HPA, Helm e troubleshooting'],skip:['Aprofundamento em providers não utilizados']},
{name:'Observabilidade',area:'SRE',hours:20,checkpoint:'SRE/DevOps',project:'Stack de métricas, logs, alertas e dashboards',course:'Trilha prática Zabbix + Grafana + Prometheus + CloudWatch',study:['Métricas e logs','Dashboards e alertas','Prometheus e Grafana','CloudWatch','SLI/SLO básicos'],skip:['Teoria SRE avançada antes da prática']},
{name:'DevSecOps',area:'Security',hours:8,checkpoint:'DevSecOps Jr.',project:'Pipeline com SAST, SCA, IaC e container scanning',course:'DevSecOps com GitHub Actions',study:['SAST e DAST','SCA/dependências','IaC scanning','Container scanning','Secrets e security gates'],skip:['Ferramentas fora do pipeline principal']},
{name:'SOC / Wazuh / Cloud Security',area:'Security',hours:24,checkpoint:'SOC Jr. / Cloud Security Jr.',project:'Mini SOC com Wazuh, Windows/Sysmon, Linux e investigação',course:'Curso completo de Wazuh — revalidar em 2028',study:['Wazuh server e agents','Windows + Sysmon','Linux/Auditd','Alertas e threat hunting','MITRE ATT&CK','Vulnerabilidades e resposta'],skip:['Integrações avançadas antes da base']}
];
const IDS=['linux','redes','zabbix','windows','aws','git','docker','terraform','cicd','k8s','observ','devsecops','soc'];modules.forEach((m,i)=>m.id=IDS[i]);const K=i=>modules[i].id;const schedule=[['Out/2026','Linux','Ubuntu Server e laboratório','Base Infra'],['Nov/2026','Redes (CCNA)','Lab de redes e troubleshooting','Base NOC'],['Dez/2026','Zabbix + Windows Server (ritmo acelerado)','Zabbix/Grafana e AD/PowerShell, aproveitando o que já usa no trabalho','Começar candidaturas NOC/Infra'],['Jan/2027','AWS','Projeto AWS 3-tier','Começar candidaturas Cloud Jr.'],['Fev/2027','Git + Docker','Repo profissional e Compose','DevOps base'],['Mar/2027','Terraform','Infra AWS como código','Cloud/DevOps Jr.'],['Abr/2027','CI/CD','Pipeline GitHub Actions','DevOps Jr.'],['Mai–Jun/2027','Kubernetes','Cluster, deploy e troubleshooting','DevOps/SRE'],['Jul–Set/2027','Observabilidade','Métricas, logs e alertas','SRE/DevOps'],['Out–Dez/2027','DevSecOps','Pipeline com security gates','DevSecOps'],['Jan–Jun/2028','SOC + Wazuh','Mini SOC','SOC/Cloud Security'],['Jul–Dez/2028','Certificações + capstone','Projetos avançados','Consolidação'],['2029','Especialização','Projetos avançados','Pleno → Sênior'],['2030+','Cloud/SRE/Security avançado','Especialização contínua','Mercado internacional como possibilidade']];
const jobs=[['NOC Jr.','Linux, redes, Zabbix e troubleshooting','Lab Zabbix/Grafana','R$ 2,5–4 mil','Após módulo 3'],['Infra Jr.','Linux, Windows/AD, DNS/DHCP, PowerShell','Lab Windows','R$ 3–5 mil','Após módulo 4'],['Cloud Jr.','AWS, IAM, VPC, EC2, RDS e CloudWatch','AWS 3-tier','R$ 4–6 mil','Após módulo 5'],['DevOps Jr.','Git, Docker, Terraform e CI/CD','Pipeline + IaC','R$ 4–7 mil','Após módulo 9'],['Cloud/DevOps Pleno','Cloud, IaC, containers, CI/CD e observabilidade','Capstone completo','R$ 6–12 mil','Médio prazo'],['Cloud Security / SOC','SIEM, logs, IAM, incidentes e cloud security','Mini SOC','R$ 7–12 mil+','Após módulo 13']];
const certs=[['CCNA (ou Network+)','Após o módulo de Redes e o lab','Alta'],['LPIC-1 ou RHCSA','Após Linux e prática','Média'],['AWS Solutions Architect Associate','Após AWS + projeto','Alta'],['AWS Cloud Practitioner','Opcional, se quiser uma entrada mais leve','Opcional'],['CKA','Após Kubernetes e prática','Futuro'],['Security+ ou equivalente','Após base de segurança','Futuro'],['Cloud Security','Após Cloud + Security','Futuro']];
const shop=[['Linux',30,'Agora ou próxima promoção'],['Redes / CCNA',35,'Escolher curso atual antes de comprar'],['Zabbix',30,'Prioridade imediata'],['AWS SAA',35,'Comprar perto de Jan/2027'],['Docker',30,'Comprar perto de Fev/2027'],['Terraform',35,'Comprar perto de Mar/2027'],['GitHub Actions',30,'Comprar perto de Abr/2027'],['Kubernetes',40,'Revalidar curso em 2027'],['Wazuh',35,'Revalidar curso em 2028']];
let data=load();function DEF(){return{v:2,projectStatus:{},projectLinks:{},projectNotes:{},journal:[],certStatus:{},purchases:{},checks:{}}}
function norm(d){let b=DEF();if(!d||typeof d!=='object')return b;for(let k in b){if(k==='v')continue;let ok=Array.isArray(b[k])?Array.isArray(d[k]):d[k]&&typeof d[k]==='object'&&!Array.isArray(d[k]);if(ok)b[k]=d[k]}return b}
function migrate(d){if(!d||d.v===2)return d;let M=['linux','zabbix','windows','aws','git','docker','terraform','cicd','k8s','observ','devsecops','soc'],C=['AWS Solutions Architect Associate','AWS Cloud Practitioner','CKA','Security+ ou equivalente','Cloud Security'],S=['Linux','Zabbix','AWS SAA','Docker','Terraform','GitHub Actions','Kubernetes','Wazuh'],o={journal:d.journal};[['projectStatus',M],['projectLinks',M],['projectNotes',M],['certStatus',C],['purchases',S]].forEach(([k,L])=>{o[k]={};for(let i in d[k]||{})if(L[i])o[k][L[i]]=d[k][i]});return o}
function load(){try{return norm(migrate(JSON.parse(store.get())))}catch{return DEF()}}
function today(){let d=new Date();return new Date(d-d.getTimezoneOffset()*6e4).toISOString().slice(0,10)}
function save(){store.set(JSON.stringify(data));document.getElementById('saved').textContent='● Salvo'}function pct(i){let m=modules[i],d=m.study.filter((_,k)=>data.checks[m.id+':'+k]).length/m.study.length,s=data.projectStatus[m.id];return Math.round(70*d+30*(s==='Concluído'?1:s==='Em andamento'?.5:0))}function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function total(){return Math.round(modules.reduce((a,_,i)=>a+pct(i),0)/modules.length)}function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function render(){dash();track();projects();timeline();career();certifications();journal();purchases()}
function go(t){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===t))}
const ST=['Não iniciado','Em andamento','Concluído'];function opts(i){return ST.map(x=>`<option ${x===(data.projectStatus[K(i)]||ST[0])?'selected':''}>${x}</option>`).join('')}
function setStatus(i,v,d){data.projectStatus[K(i)]=v;save();render();if(d)details(i)}
function chk(id,k,v){data.checks[id+':'+k]=v;save();let e=document.getElementById('dpct');if(e)e.textContent=pct(modules.findIndex(m=>m.id===id));dash()}
function dash(){let done=modules.filter((_,i)=>pct(i)===100).length,hrs=data.journal.reduce((a,r)=>a+Number(r.hours||0),0),i=modules.findIndex((_,i)=>pct(i)<100);if(i<0)i=modules.length-1;document.getElementById('dashboard').innerHTML=`<div class="grid g4"><div class="card"><div class="metric">${total()}%</div><div class="muted">Progresso geral</div><div class="progress" style="margin-top:12px"><span style="width:${total()}%"></span></div></div><div class="card"><div class="metric">${done}/${modules.length}</div><div class="muted">Módulos concluídos</div></div><div class="card"><div class="metric">${Object.values(data.projectStatus).filter(x=>x==='Concluído').length}/${modules.length}</div><div class="muted">Projetos concluídos</div></div><div class="card"><div class="metric">${hrs.toFixed(1)}h</div><div class="muted">Horas registradas</div></div></div><div class="grid g2" style="margin-top:15px"><div class="card"><h2>🚀 Próximo passo</h2><h3>${modules[i].name}</h3><p class="muted">Checkpoint: ${modules[i].checkpoint} • ${modules[i].hours}h-alvo</p><div class="barrow"><span>Progresso</span><b>${pct(i)}%</b></div><div class="progress"><span style="width:${pct(i)}%"></span></div><p><b>Projeto:</b> ${modules[i].project}</p><button class="btn primary" onclick="details(${i})">Abrir módulo</button></div><div class="card"><h2>📌 Método de estudo</h2><div class="grid g2"><div><b>30%</b><p class="muted">Curso</p></div><div><b>50%</b><p class="muted">Laboratório e projeto</p></div><div><b>20%</b><p class="muted">Documentação e revisão</p></div><div><b>Critério</b><p class="muted">Concluir quando conseguir fazer sozinho.</p></div></div></div></div>`}
function track(){document.getElementById('trilha').innerHTML=`<h2>🎓 Trilha completa — ${total()}%</h2><div class="grid">${modules.map((m,i)=>`<article class="card module"><div class="num">${i+1}</div><div><span class="badge">${m.area}</span><span class="badge ${pct(i)===100?'success':pct(i)>0?'warn':'gray'}">${pct(i)===100?'Concluído':pct(i)>0?'Em andamento':'Não iniciado'}</span><h3>${m.name}</h3><p class="muted">Curso: ${m.course}</p><p class="muted">Checkpoint: ${m.checkpoint} • ${m.hours}h-alvo</p><p><b>Projeto:</b> ${m.project}</p><div class="barrow"><span>Progresso</span><b>${pct(i)}%</b></div><div class="progress"><span style="width:${pct(i)}%"></span></div></div><div class="actions"><button class="btn" onclick="details(${i})">Detalhes</button></div></article>`).join('')}</div>`}
function details(i){let m=modules[i];go('trilha');document.getElementById('trilha').innerHTML=`<div class="card"><button class="btn" onclick="track()">← Voltar à trilha</button><h2 style="margin-top:15px">${i+1}. ${m.name}</h2><p class="muted">${m.area} • ${m.hours}h • ${m.checkpoint}</p><h3>Curso recomendado</h3><p>${m.course}</p><h3>O que estudar</h3>${m.study.map((x,k)=>`<label style="display:block;margin:8px 0"><input type="checkbox" ${data.checks[m.id+':'+k]?'checked':''} onchange="chk('${m.id}',${k},this.checked)"> ${x}</label>`).join('')}<h3>O que pode pular/reduzir</h3>${m.skip.map(x=>`<p class="muted">• ${x}</p>`).join('')}<h3>Projeto obrigatório</h3><p>${m.project}</p><p><b>Progresso: <span id="dpct">${pct(i)}</span>%</b> <span class="muted">(70% checklist + 30% projeto)</span></p><label class="muted">Status do projeto<select class="field" onchange="setStatus(${i},this.value,1)">${opts(i)}</select></label></div>`}
function projects(){document.getElementById('projetos').innerHTML=`<h2>🧪 Projetos práticos</h2><div class="grid">${modules.map((m,i)=>`<div class="card"><span class="badge">${i+1}. ${m.name}</span><h3>${m.project}</h3><p class="muted">Entregáveis: ambiente funcional, README, evidências e lições aprendidas.</p><label class="muted">Status<select class="field" onchange="setStatus(${i},this.value)">${opts(i)}</select></label><label class="muted">Link GitHub / evidência<input class="field" value="${esc(data.projectLinks[K(i)]||'')}" onchange="data.projectLinks[K(${i})]=this.value;save()" placeholder="Cole o link aqui"></label><label class="muted">Observações<textarea class="field" onchange="data.projectNotes[K(${i})]=this.value;save()">${esc(data.projectNotes[K(i)]||'')}</textarea></label></div>`).join('')}</div>`}
function timeline(){document.getElementById('cronograma').innerHTML=`<h2>📅 Cronograma proposto</h2><div class="timeline">${schedule.map(x=>`<article><div class="date">${x[0]}</div><div class="card"><b>${x[1]}</b><p>${x[2]}</p><span class="badge">${x[3]}</span></div></article>`).join('')}</div><p class="note">Cronograma flexível: ajuste à sua carga horária, trabalho e entrevistas. Priorize prática e candidaturas quando atingir os checkpoints.</p>`}
function career(){document.getElementById('carreira').innerHTML=`<h2>💼 Checkpoints de carreira</h2><div class="wide"><table class="table"><tr><th>Cargo</th><th>Conhecimento mínimo</th><th>Prova prática</th><th>Faixa salarial indicativa</th><th>Quando aplicar</th></tr>${jobs.map(j=>`<tr><td><b>${j[0]}</b></td><td>${j[1]}</td><td>${j[2]}</td><td><b style="color:#047857">${j[3]}</b></td><td><span class="badge success">${j[4]}</span></td></tr>`).join('')}</table></div><p class="note">Faixas aproximadas e não verificadas: calibre com vagas reais (quem já tem anos de suporte pode mirar vagas plenas). Variam por região, empresa, senioridade, inglês e regime de contratação.</p>`}
function certifications(){document.getElementById('certs').innerHTML=`<h2>📜 Certificações</h2><div class="wide"><table class="table"><tr><th>Certificação</th><th>Quando</th><th>Prioridade</th><th>Status</th></tr>${certs.map((c,i)=>`<tr><td><b>${c[0]}</b></td><td>${c[1]}</td><td>${c[2]}</td><td><select class="field" onchange="data.certStatus['${c[0]}']=this.value;save()">${['Considerar','Planejada','Estudando','Concluída'].map(v=>`<option ${v===(data.certStatus[c[0]]||'Considerar')?'selected':''}>${v}</option>`).join('')}</select></td></tr>`).join('')}</table></div>`}
function journal(){document.getElementById('diario').innerHTML=`<h2>⏱️ Diário de estudos</h2><div class="card"><form id="jf" class="form"><label>Data<input name="date" type="date" value="${today()}" required></label><label>Horas<input name="hours" type="number" min="0" step=".25" required></label><label>Módulo<select name="module">${modules.map(m=>`<option>${m.name}</option>`).join('')}</select></label><label>Dificuldade (1–5)<input name="difficulty" type="number" min="1" max="5" value="3"></label><label style="grid-column:1/-1">O que estudou/praticou<textarea name="notes" required></textarea></label><button class="btn primary">Registrar estudo</button></form></div><div class="wide" style="margin-top:15px"><table class="table"><tr><th>Data</th><th>Módulo</th><th>Horas</th><th>Dificuldade</th><th>Registro</th><th></th></tr>${data.journal.slice().reverse().map((r,k)=>`<tr><td>${r.date}</td><td>${r.module}</td><td>${r.hours}</td><td>${r.difficulty}/5</td><td>${esc(r.notes)}</td><td><button class="btn" onclick="delJournal(${data.journal.length-1-k})">Excluir</button></td></tr>`).join('')}</table></div>`;document.getElementById('jf').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);data.journal.push({date:f.get('date'),hours:f.get('hours'),module:f.get('module'),difficulty:f.get('difficulty'),notes:f.get('notes')});save();render();toast('Estudo registrado!')}}function delJournal(i){data.journal.splice(i,1);save();render()}
function purchases(){document.getElementById('compras').innerHTML=`<h2>💰 Controle de compras</h2><div class="card"><b>Preço-alvo Udemy:</b> R$ 20–30 excelente • R$ 30–50 aceitável • R$ 50–70 só se excepcional • acima de R$ 80 evitar.<p class="note">Os preços variam. Revalide os cursos próximos à data de estudo, especialmente Kubernetes e Wazuh.</p></div><div class="wide" style="margin-top:15px"><table class="table"><tr><th>Curso</th><th>Preço-alvo</th><th>Preço encontrado (R$)</th><th>Comprar?</th><th>Data</th><th>Observação</th></tr>${shop.map((x,i)=>{let p=data.purchases[x[0]]||{};return `<tr><td><b>${x[0]}</b></td><td>R$ ${x[1]}</td><td><input class="field" type="number" step=".01" value="${p.price||''}" onchange="purchase('${x[0]}','price',this.value)"></td><td><select class="field" onchange="purchase('${x[0]}','decision',this.value)">${['Não','Talvez','Sim'].map(v=>`<option ${v===(p.decision||'Não')?'selected':''}>${v}</option>`).join('')}</select></td><td><input class="field" type="date" value="${p.date||''}" onchange="purchase('${x[0]}','date',this.value)"></td><td>${x[2]}</td></tr>`}).join('')}</table></div>`}function purchase(i,k,v){data.purchases[i]??={};data.purchases[i][k]=v;save()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.tab));document.getElementById('export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='pos-udemy-backup.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('import').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{data=norm(migrate(JSON.parse(r.result)));save();render();toast('Backup importado!')}catch{toast('Arquivo inválido')}};r.readAsText(f)};document.getElementById('reset').onclick=()=>{if(confirm('Apagar todo o progresso, projetos, diário e compras?')){data=DEF();save();render();toast('Progresso resetado')}};render();
